env:
  - ANT_HOME=$PWD/tools/apache-ant-1.8.3
  - ANT_OPTS=-Xmx1024m
language: java
jdk:
  - openjdk7
  - openjdk6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "ant -lib $ANT_HOME\lib\build build"
notifications:
  email:
    - travis.middleman@stuart-taylor.net
on_failure: always
on_success: change
